# air.toml - Configuration file for Air live reloading

root = "."


[build]
    bin = "./tmp/main"
    cmd = "templ generate & go build -o tmp/main ./cmd/"
    delay = 0
    exclude_dir = ["assets", "tmp", "vendor", "testdata"]
    exclude_file = []
    exclude_regex = ["_test.go", "_templ.go"]
    include_ext = ["go", "tpl", "tmpl", "templ", "html"]

[log]
  main_only = false
  time = false
